app = "slack-daily-trivia"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "trivia_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true

[experimental]
  auto_rollback = true
