app = "slack-daily-trivia"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "trivia_data"
  destination = "/data"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[experimental]
  auto_rollback = true
